[deps]
Crafts = "b2ff1c92-5c3b-499f-8ce1-93fd6946a36f"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Roly = "1621a601-f9d4-49dc-b032-1328811fec3a"

[sources]
Roly = {url = "https://github.com/goodrichgroup/Roly.jl.git", rev = "main"}

[compat]
Documenter = "1"
