"""
    FaceLattice

The faces of a cone or polytope, grouped by dimension.

  - `levels[k+1]`: the faces of dimension `k`, each a `BitVector` over the generators
  - `dualsets[k+1]`: the facets containing each face, when `facetsets=true` was passed
  - `covers[k+1]`: pairs `(i, j)` linking face `i` of dimension `k` to face `j` of dimension `k+1`,
    when `covers=true` was passed
  - `dual`: whether the lattice was built from the facets rather than the generators
"""
struct FaceLattice
    levels::Vector{Vector{BitVector}}
    dualsets::Union{Nothing,Vector{Vector{BitVector}}}
    covers::Union{Nothing,Vector{Vector{Tuple{Int,Int}}}}
    dual::Bool
end

"""
    faces(L::FaceLattice, k)

Return the faces of dimension `k`, each a `BitVector` over the generators.
"""
faces(L::FaceLattice, k::Integer) = L.levels[k + 1]

"""
    fvector(L::FaceLattice)

Return the number of faces of each dimension, starting at dimension zero.
"""
fvector(L::FaceLattice) = length.(L.levels)

"""
    covers(L::FaceLattice, k)

Return the cover relations from dimension `k` to `k+1` as `(i, j)` index pairs.
"""
function covers(L::FaceLattice, k::Integer)
    L.covers === nothing &&
        throw(ArgumentError("this lattice was built without cover relations; pass `covers=true`"))
    return L.covers[k + 1]
end

Base.show(io::IO, L::FaceLattice) =
    print(io, "FaceLattice[f=", join(fvector(L), ","), L.dual ? ", dual]" : "]")

# The closed set generated by `A`: intersect every facet that contains it. `incident` is reused
# across calls and comes back holding those facets, which is the face's dual set.
function _closure!(out::BitVector, incident::BitVector, A::BitVector, rows::Vector{BitVector})
    fill!(out, true)
    for (j, F) in pairs(rows)
        sub = true
        @inbounds for w in eachindex(A.chunks)
            if A.chunks[w] & ~F.chunks[w] != 0
                sub = false
                break
            end
        end
        incident[j] = sub
        sub && (out .&= F)
    end
    return out
end

_strictsubset(a::BitVector, b::BitVector) = a != b && all(i -> !a[i] | b[i], eachindex(a))

"""
    facelattice(incidence; maxdim, dual=false, covers=false, facetsets=false)

Enumerate the faces of a cone or polytope from its generator-facet incidences.

  - `incidence[i, j]`: whether generator `j` lies on facet `i`
  - `maxdim`: stop after this dimension; the default enumerates the whole lattice
  - `dual`: walk down from the facets instead of up from the generators
  - `covers`: also return the cover relations
  - `facetsets`: also tag each face with the facets containing it

Returns a [`FaceLattice`](@ref).
"""
function facelattice(incidence::AbstractMatrix{Bool}; maxdim=typemax(Int), dual=false,
                     covers=false, facetsets=false)
    inc = dual ? permutedims(incidence) : incidence
    nfacets, ngens = size(inc)
    rows = [BitVector(view(inc, i, :)) for i in 1:nfacets]

    out = falses(ngens)
    incident = falses(nfacets)

    bottom = copy(_closure!(out, incident, falses(ngens), rows))
    levels = [[bottom]]
    duals = facetsets ? [[copy(incident)]] : nothing
    edges = covers ? Vector{Vector{Tuple{Int,Int}}}() : nothing

    for _ in 1:maxdim
        prev = levels[end]
        nxt = BitVector[]
        nxtduals = facetsets ? BitVector[] : nothing
        index = Dict{BitVector,Int}()
        levelcovers = covers ? Tuple{Int,Int}[] : nothing

        for (p, F) in pairs(prev)
            # Every closure above F, then the minimal ones among them: those are exactly the faces
            # that cover F, with no linear algebra and no tolerance.
            cands = BitVector[]
            canddual = facetsets ? BitVector[] : nothing
            for a in 1:ngens
                F[a] && continue
                A = copy(F)
                A[a] = true
                G = copy(_closure!(out, incident, A, rows))
                any(==(G), cands) && continue
                push!(cands, G)
                facetsets && push!(canddual, copy(incident))
            end

            for (c, G) in pairs(cands)
                any(H -> _strictsubset(H, G), cands) && continue
                k = get(index, G, 0)
                if k == 0
                    push!(nxt, G)
                    facetsets && push!(nxtduals, canddual[c])
                    k = length(nxt)
                    index[G] = k
                end
                covers && push!(levelcovers, (p, k))
            end
        end

        isempty(nxt) && break
        push!(levels, nxt)
        facetsets && push!(duals, nxtduals)
        covers && push!(edges, levelcovers)
    end

    return FaceLattice(levels, duals, edges, dual)
end

"""
    facelattice(A, b; kwargs...)

Enumerate the faces of the cone `A*x <= b`, computing its generators and incidences first.
"""
function facelattice(A::AbstractMatrix{<:LrsNum}, b::AbstractVector{<:LrsNum}; linearity=Int[],
                     kwargs...)
    rays, verts = extremerays(A, b; linearity)
    V = vcat(rays, verts)
    isempty(V) && throw(ArgumentError("the system `A*x <= b` has no generators"))
    flags = [trues(size(rays, 1)); falses(size(verts, 1))]
    _, _, inc = facetsof(V; rays=flags)
    return facelattice(inc; kwargs...)
end
